---
title: "analysis"
output: html_document
---

```{r setup}

## Clear workspace
rm(list=ls())

## The "pacman" package automatically install missing packages and load them
if (!require("pacman")) install.packages("pacman", repos = 'https://stat.ethz.ch/CRAN/'); 

pacman::p_load(
  # data processing
  tidyverse,  # collection of the tidyverse packages
  stringr,    #   - for string functions
  forcats,    #   - utility functions for working with factor levels
  lubridate,  #   - utility for parsing and performing arithematic on dates 
  tools,      #   - for package development, administration and documentation
  data.table, #   - for data manipulation 
  tibble     #   - to create data frames
)
```

## Data Import

```{r import}

# Create a function that imports all .sd2 files from a directory

import_raw_data_file <- function(dir_name, condition_name) {
  
  file_list <- list.files(path = file.path("02 raw data", dir_name), pattern = "*.sd2", recursive = TRUE, full.names = TRUE)
  
  raw_data <- do.call("rbind", lapply(file_list, function(filename)
  data.frame(read.delim(filename, sep = ","))))
  
  # Overwrite Condition because it was used inconsistently during the experiments
  # Therefore, the correct condition needs to be given as a function parameter
  raw_data$Condition = condition_name
  
  return(raw_data)
  
}

# import all .sd2 files from all conditions and combine them into a single table

data_raw <- rbind(
  import_raw_data_file("1_trackpad", "trackpad"),
  import_raw_data_file("2_index finger", "index finger"),
  import_raw_data_file("3_thumb", "thumb"),
  import_raw_data_file("4_sway", "sway")
)

data_raw$Condition <- as.factor(data_raw$Condition)
```

## Data Clean Up

```{r clean up}

# Keep only the columns of interest and give them more readable names

data_raw <- data_raw %>% 
  select(
    Participant,
    Condition,
    Amplitude = A,
    Width = W,
    PointingTime = PT.ms.,
    SelectionTime = ST.ms.,
    MovementTime = MT.ms.,
    ErrorRate = ER...,
    Throughput = TP.bps.
  )

# Spread the table to make it more suited for further analysis

data_pointing_time <- data_raw %>%
  select(Participant:Width, PointingTime) %>% 
  spread(key = Condition, value = PointingTime) %>% 
  select(Participant:Width,
         PointingTime_trackpad = trackpad,
         PointingTime_index_finger = 'index finger',
         PointingTime_thumb = thumb,
         PointingTime_sway = sway
  )

data_selection_time <- data_raw %>%
  select(Participant:Width, SelectionTime) %>% 
  spread(key = Condition, value = SelectionTime) %>% 
  select(Participant:Width,
         SelectionTime_trackpad = trackpad,
         SelectionTime_index_finger = 'index finger',
         SelectionTime_thumb = thumb,
         SelectionTime_sway = sway
  )

data_movement_time <- data_raw %>%
  select(Participant:Width, MovementTime) %>% 
  spread(key = Condition, value = MovementTime) %>% 
  select(Participant:Width,
         MovementTime_trackpad = trackpad,
         MovementTime_index_finger = 'index finger',
         MovementTime_thumb = thumb,
         MovementTime_sway = sway
  )

data_error_rate <- data_raw %>%
  select(Participant:Width, ErrorRate) %>% 
  spread(key = Condition, value = ErrorRate) %>% 
  select(Participant:Width,
         ErrorRate_trackpad = trackpad,
         ErrorRate_index_finger = 'index finger',
         ErrorRate_thumb = thumb,
         ErrorRate_sway = sway
  )

data_throughput <- data_raw %>%
  select(Participant:Width, Throughput) %>% 
  spread(key = Condition, value = Throughput) %>% 
  select(Participant:Width,
         Throughput_trackpad = trackpad,
         Throughput_index_finger = 'index finger',
         Throughput_thumb = thumb,
         Throughput_sway = sway
  )

data_spread <- merge(data_pointing_time, data_selection_time)
data_spread <- merge(data_spread, data_movement_time)
data_spread <- merge(data_spread, data_error_rate)
data_spread <- merge(data_spread, data_throughput)

data_spread <- data_spread %>% 
  arrange(Participant, Amplitude, Width)

## In our analysis, we will not focus on the differences in amplitude and width. For this reason, we use the average for each participant for each mode.
data_mean_per_participant <- data_spread %>%
  group_by(Participant) %>% 
  summarise(PointingTime_trackpad = mean(PointingTime_trackpad), PointingTime_index_finger = mean(PointingTime_index_finger), PointingTime_thumb = mean(PointingTime_thumb), PointingTime_sway = mean(PointingTime_sway), SelectionTime_trackpad = mean(SelectionTime_trackpad), SelectionTime_index_finger = mean(SelectionTime_index_finger), SelectionTime_thumb = mean(SelectionTime_thumb), SelectionTime_sway = mean(SelectionTime_sway), MovementTime_trackpad = mean(MovementTime_trackpad), MovementTime_index_finger = mean(MovementTime_index_finger), MovementTime_thumb = mean(MovementTime_thumb), MovementTime_sway = mean(MovementTime_sway), ErrorRate_trackpad = mean(ErrorRate_trackpad), ErrorRate_index_finger = mean(ErrorRate_index_finger), ErrorRate_thumb = mean(ErrorRate_thumb), ErrorRate_sway = mean(ErrorRate_sway), Throughput_trackpad = mean(Throughput_trackpad), Throughput_index_finger = mean(Throughput_index_finger), Throughput_thumb = mean(Throughput_thumb), Throughput_sway = mean(Throughput_sway))


## We are intersted in the difference in speed and accuracy between the trackpad (baseline input mode) and the three mobile modes: with index finger, thumb and in sway mode.
# Difference in speed
speed_difference_to_trackpad <- data_spread %>% 
  transmute(
    Participant,
    Amplitude,
    Width,
    IndexFinger_diff = MovementTime_index_finger - MovementTime_trackpad,
    Thumb_diff = MovementTime_thumb - MovementTime_trackpad,
    Sway_diff = MovementTime_sway - MovementTime_trackpad
  )

speed_difference_to_trackpad_aggregated <- speed_difference_to_trackpad %>% 
  group_by(Participant) %>% 
  summarise(meanIndexFingerSpeed = mean(IndexFinger_diff), meanThumbSpeed = mean(Thumb_diff), meanSwaySpeed = mean(Sway_diff))

# Difference in accuracy
accuracy_difference_to_trackpad <- data_spread %>% 
  transmute(
    Participant,
    Amplitude,
    Width,
    IndexFinger_diff = ErrorRate_index_finger - ErrorRate_trackpad,
    Thumb_diff = ErrorRate_thumb - ErrorRate_trackpad,
    Sway_diff = ErrorRate_sway - ErrorRate_trackpad
  )

accuracy_difference_to_trackpad_aggregated <- speed_difference_to_trackpad %>% 
  group_by(Participant) %>% 
  summarise(meanIndexFingerSpeed = mean(IndexFinger_diff), meanThumbSpeed = mean(Thumb_diff), meanSwaySpeed = mean(Sway_diff))

```
## Summary 
```{r summary}
summary(speed_difference_to_trackpad_aggregated)
```

## Plots

```{r boxplot for troughputs}
# Plot 1: Throughput for the 4 input modes for the eight participants

# Boxplot of the average throughput that participants have for one pointing task
boxplot_throughput <- boxplot(data_throughput[4:7], names = c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'), xlab = 'Input Mode',
                              ylab = 'Throughput in bits/s')
```

```{r lineplot for troughputs}
# Analysis of average troughput per input mode trial for each participant
average_troughput_per_participant <- aggregate(data_throughput[4:7], list(data_throughput$Participant), mean) %>%
  rename('Participant' = Group.1, 'Trackpad' = Throughput_trackpad, 'Index Finger' = Throughput_index_finger, 'Thumb' = Throughput_thumb, 'Sway Mode' = Throughput_sway) %>%
  gather(key = Input_Mode, value = Average_Throughput, c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'))

ggplot (data = average_troughput_per_participant, mapping = aes(x = fct_relevel(Input_Mode, "Trackpad", "Index Finger", "Thumb", "Sway Mode"), y = Average_Throughput, col = Participant, group = Participant)) +
  geom_point() +
  geom_line() +
  labs(x = 'Input Mode', y = 'Throughput in bits/s')
```

```{r boxplot for movement time}
# Plot 2: Speed for the 4 input modes for the eight participants

# Boxplot of the average time participant needed to finish one pointing task
boxplot_movement_time <- boxplot(data_movement_time[4:7], names = c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'), xlab = 'Input Mode', ylab = 'Movement Time in ms')
```

```{r lineplot for movement time}
# Analysis of average moventtime per input mode trial for each participant
average_movement_time_per_participant <- aggregate(data_movement_time[4:7], list(data_movement_time$Participant), mean) %>%
  rename('Participant' = Group.1, 'Trackpad' = MovementTime_trackpad, 'Index Finger' = MovementTime_index_finger, 'Thumb' = MovementTime_thumb, 'Sway Mode' = MovementTime_sway) %>%
  gather(key = Input_Mode, value = Average_Movement_Time, c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'))

ggplot (data = average_movement_time_per_participant, mapping = aes(x = fct_relevel(Input_Mode, "Trackpad", "Index Finger", "Thumb", "Sway Mode"), y = Average_Movement_Time, col = Participant, group = Participant)) +
  geom_point() +
  geom_line() +
  labs(x = 'Input Mode', y = 'Movement Time in ms' )
  # ggtitle('Average movement time participants used to finish one pointing task depending on the input mode they used.')


```


```{r boxplot for selection time}
# Plot 1: Selection time for the 4 input modes for the eight participants

# Boxplot of the average throughput that participants have for one pointing task
boxplot_selection_time <- boxplot(data_selection_time[4:7], names = c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'), xlab = 'Input Mode',     ylab = 'Selection Time in ms')

```

```{r lineplot for selection time}
# Analysis of average troughput per input mode trial for each participant
average_selection_time_per_participant <- aggregate(data_selection_time[4:7], list(data_selection_time$Participant), mean) %>%
  rename('Participant' = Group.1, 'Trackpad' = Throughput_trackpad, 'Index Finger' = Throughput_index_finger, 'Thumb' = Throughput_thumb, 'Sway Mode' = Throughput_sway) %>%
  gather(key = Input_Mode, value = Average_Throughput, c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'))

ggplot (data = average_selection_time_per_participant, mapping = aes(x = fct_relevel(Input_Mode, "Trackpad", "Index Finger", "Thumb", "Sway Mode"), y = Average_Throughput, col = Participant, group = Participant)) +
  geom_point() +
  geom_line() +
  labs(x = 'Input Mode', y = 'Throughput in bits/s')

```


```{r boxplot for pointing time}
# Plot 1: pointing time for the 4 input modes for the eight participants

# Boxplot of the average throughput that participants have for one pointing task
boxplot_pointing_time <- boxplot(data_throughput[4:7], names = c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'), xlab = 'Input Mode', ylab = 'Throughput in bits/s')
```

```{r lineplot for pointing time}
# Analysis of average troughput per input mode trial for each participant
average_troughput_per_participant <- aggregate(data_throughput[4:7], list(data_throughput$Participant), mean) %>%
  rename('Participant' = Group.1, 'Trackpad' = Throughput_trackpad, 'Index Finger' = Throughput_index_finger, 'Thumb' = Throughput_thumb, 'Sway Mode' = Throughput_sway) %>%
  gather(key = Input_Mode, value = Average_Throughput, c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'))

ggplot (data = average_troughput_per_participant, mapping = aes(x = fct_relevel(Input_Mode, "Trackpad", "Index Finger", "Thumb", "Sway Mode"), y = Average_Throughput, col = Participant, group = Participant)) +
  geom_point() +
  geom_line() +
  labs(x = 'Input Mode', y = 'Throughput in bits/s')
```



```{r plots for error rate}
# Plot 3: Accuracy for the 4 input modes for the eight participants

# Boxplot of the average error rate that participants have for one pointing task
boxplot_error_rate <- boxplot(data_error_rate[4:7], names = c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'), xlab = 'Input Mode',
                              ylab = 'Error Rate in %')


# Analysis of average error rate per input mode trial for each participant
average_error_rate_per_participant <- aggregate(data_error_rate[4:7], list(data_error_rate$Participant), mean) %>%
  rename('Participant' = Group.1, 'Trackpad' = ErrorRate_trackpad, 'Index Finger' = ErrorRate_index_finger, 'Thumb' = ErrorRate_thumb, 'Sway Mode' = ErrorRate_sway) %>%
  gather(key = Input_Mode, value = Average_Error_Rate, c('Trackpad', 'Index Finger', 'Thumb', 'Sway Mode'))

ggplot (data = average_error_rate_per_participant, mapping = aes(x = fct_relevel(Input_Mode, "Trackpad", "Index Finger", "Thumb", "Sway Mode"), y = Average_Error_Rate, col = Participant, group = Participant)) +
  geom_point() +
  geom_line() +
  labs(x = 'Input Mode', y = 'Error Rate in %')

```

## Statistical analysis
```{r anova speed}
fit_speed <- aov(MovementTime ~ Condition, data_raw)
summary(fit_speed)
m.res <- resid(fit_speed)
plot(data_raw$MovementTime, m.res, ylab="Residuals", xlab="MovementTime")
```

```{r anova accuracy}
fit_accuracy <- aov(ErrorRate ~ Condition, data_raw)
summary(fit_accuracy)
m.res <- resid(fit_accuracy)
plot(data_raw$ErrorRate, m.res, ylab="Residuals", xlab="ErrorRate")
```

```{r anovy throughput}
fit_throughput <- aov(Throughput ~ Condition, data_raw)
summary(fit_throughput)
m.res <- resid(fit_throughput)
plot(data_raw$Throughput, m.res, ylab="Residuals", xlab="Throughput")
```

We understand from these ANOVA tests that not all the means are equals. We still have to search which pairs of conditions. For that purpose, we condcut a Post Hoc Test.

```{r }
TukeyHSD(fit_speed)

par(mar=c(5,10,4,2)+0.1) # Add additional margin to the left for fitting the label size

# This hack is used to set a more specific title than the default one generated by R
par(col.main = "white")
plot(TukeyHSD(fit_speed), las=1)
par(col.main = "black")
title(main = "Speed - 95% family-wise confidence level")
```

```{r }
TukeyHSD(fit_accuracy)

par(mar=c(5,10,4,2)+0.1) # Add additional margin to the left for fitting the label size

# This hack is used to set a more specific title than the default one generated by R
par(col.main = "white")
plot(TukeyHSD(fit_accuracy), las=1)
par(col.main = "black")
title(main = "Accuracy - 95% family-wise confidence level")
```

```{r }
TukeyHSD(fit_throughput)

par(mar=c(5,10,4,2)+0.1) # Add additional margin to the left for fitting the label size

# This hack is used to set a more specific title than the default one generated by R
par(col.main = "white")
plot(TukeyHSD(fit_throughput), las=1)
par(col.main = "black")
title(main = "Throughput - 95% family-wise confidence level")
```

